name: "MochaUI"

version: "0.9.8-dev"

exports: "mochaui.js"

web: "[mochaui.com](http://mochaui.com/)"

description: "MochaUI, A web applications user interface library"

license: "[MIT License](http://mochaui.com/demo/license.txt)"

copyright: "&copy; [AUTHORS.txt]"

authors:
  - "[Chris Doty](http://polaropposite.com/)"
  - "[Greg Houston](http://greghoustondesign.com/)"
  - "Scott F. Frederick"
  - "Joel Lindau"
  - "Harry Roberts"

sources:
  - "src/mui/core.js"
  - "src/mui/update.js"
  - "src/mui/window.js"
  - "src/mui/modal.js"
  - "src/mui/layout.js"
  - "src/mui/dock.js"
  - "src/mui/tabs.js"